server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
    external_labels:
      job: microservices-example

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=microservices-example"]

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
        replacement: "$1"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: "project"

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            message: message
            service: service
      - labels:
          level:
          service:
          container:
          project:
